config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin, path: Spree.admin_path do
    resources :relation_types
    resources :products, only: [] do
      get :related, on: :member
      resources :relations do
        collection do
          post :update_positions
        end
      end
    end
  end

  namespace :api, defaults: { format: 'json' } do
    resources :products, only: [] do
      get :related, on: :member
      resources :relations do
        collection do
          post :update_positions
        end
      end
    end
  end
end

app/views/spree/admin/products/_related_products.html.erb
<% content_for(:page_tabs) do %>
  <%= content_tag :li, class: 'nav-item' do %>
    <%= link_to_with_icon 'resize-small',
      Spree.t(:related_products),
      related_admin_product_url(@product),
      class: "nav-link #{'active' if current == :related_products}" %>

  <% end if can?(:admin, Spree::Product) && !@product.deleted? %>
<% end %>

app/views/spree/admin/products/_related_products_table.html.erb
<table class="table sortable" data-hook="products_table" data-sortable-link="<%= update_positions_admin_product_relations_url(@product) %>">
   <colgroup>
    <col style="width: 5%" />
    <col style="width: 35%" />
    <col style="width: 30%" />
    <col style="width: 25%" />
    <col style="width: 5%" />
  </colgroup>
  <thead>
    <tr data-hook="products_header">
      <th></th>
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:type) %></th>
      <th><%= Spree.t(:discount_amount) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% product.relations.each do |relation| %>
      <tr id="<%= spree_dom_id relation %>" data-hook="products_row">
        <td class="handle move-handle">
          <% if Spree.version.to_d >= 4.2 && defined?(svg_icon) %>
            <%= svg_icon name: "sort.svg", width: '18', height: '18' %>
          <% else %>
            <span class="icon icon-move handle"></span>
          <% end %>
        </td>
        <td><%= link_to relation.related_to.name, admin_product_path(relation.related_to) %></td>
        <td><%= relation.relation_type.name %></td>
        <td>
          <%= form_for relation, url: admin_product_relation_path(relation.relatable, relation) do |f| %>
            <div class="input-group justify-content-center">
              <%= f.text_field :discount_amount, class: 'form-control text-center my-1 w-50' %>
              <span class="input-group-btn">
                <%= f.button Spree.t(:update), type: 'submit', class: 'btn btn-primary m-1' %>
              </span>
            </div>
          <% end %>
        </td>
        <td class="actions">
          <%= link_to_delete relation, url: admin_product_relation_url(relation.relatable, relation), no_text: true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/products/related.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: 'Related Products' } %>
<%= render partial: 'spree/admin/variants/autocomplete', formats: :js %>

<%= csrf_meta_tag %>

<% if frontend_available? %>
  <%= content_for :page_actions do %>
    <%=
      button_link_to(
        Spree.t(:preview_product),
        spree.product_url(@product),
        class: 'btn-outline-secondary', icon: 'eye-open', id: 'admin_preview_product', target: :blank
      )
    %>
  <% end %>
<% end %>

<% if @relation_types.empty? %>
  <div class="alert alert-warning no-objects-found">
    <%= Spree.t(:no_relation_types) %>
  </div>
<% else %>
  <div id="add-line-item">
    <fieldset>
      <legend><%= Spree.t(:add_related_product) %></legend>
      <div class="row">
        <div id="related_product_name" class="col-md-12 col-xl-5">
          <div class="form-group">
            <%= label_tag :add_variant_name, Spree.t(:name_or_sku_short) %>
            <% if Spree.version.to_d >= 4.2 %>
              <%= select_tag :add_variant_name, nil , class: 'variant_autocomplete d-block w-100' %>
            <% else %>
              <%= hidden_field_tag :add_variant_name, '', class: 'variant_autocomplete', style: "display: block !important;" %>
            <% end %>
          </div>
        </div>
        <div id="related_product_type" class="col-md-7 col-xl-4">
          <div class="form-group">
            <%= label_tag :add_type, Spree.t(:type) %>
            <%= select_tag :add_type, options_for_select(@relation_types.map { |rt| [rt.name, rt.id] }), class: 'select2' %>
          </div>
        </div>
        <div id="related_product_discount" class="col-md-5 col-xl-3">
          <div class="form-group">
            <%= label_tag :add_discount, Spree.t(:discount_amount) %>
            <div class="input-group">
              <%= text_field_tag :add_discount, 0.0, class: 'form-control text-center' %>
              <span class="input-group-btn">
                <%= button_link_to Spree.t(:add), admin_product_relations_url(@product), icon: 'add', class: 'btn-success my-0', id: 'add_related_product', data: { update: 'products-table-wrapper' } %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </fieldset>
  </div>

  <div id="products-table-wrapper">
    <%= render 'related_products_table', product: @product %>
  </div>

  <%= content_for :head do %>
    <script type="text/javascript">
      var expand_variants = false;
      $(document).on('click', '#add_related_product', function(){
        if($('#add_variant_name').val() == '') { return false; }
        update_target = $(this).data('update');
        $.ajax({
          dataType: 'script',
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
          url: this.href,
          type: 'POST',
          data: {
            'relation[related_to_type]' : 'Product',
            'relation[related_to_id]': $('#add_variant_name').val(),
            'relation[relation_type_id]': $('#add_type').val(),
            'relation[discount_amount]' : $('#add_discount').val()
          }
        });
        return false;
      });

      $(function () {
        $('#add_variant_name.variant_autocomplete').variantAutocomplete();
      });
    </script>
  <% end %>
<% end %>